@baseUrl = http://localhost:3333
@authToken = eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI5YzJkYzUzOC02N2M2LTRhN2YtYTE0Mi0wYzZjYjI0NDE1NWEiLCJpYXQiOjE3MDI2MDM0Njl9.dk8qS1JHxuWpXY8I5dDXdr_nBOZERBQ6GNK7GVdcor7Vla8Y_nFt1Y8gCHIJ9U-6O3Fvyy658lGet_mfHpLYj4O2lWNywXGz3RME9QSCTYuuDACSymERoFpCpyoYN3F88JGws8rbxFgTQgUJedyowNtOPySsAST4g-kgvXZdXIE5Rkda4zjUIslnCgbuoVT7oHbECxmsdoaOO3fKm58WnjyNTE-LdB-nZx2CQD35AHiOR8pbVY24o4VUKrWeZ7jYmlnb9OZoeKOfQ43EVf9FxX3gwijX4QUljebhlriTtgtlLPIL0HeicHy98OENXb9pU_zVo-teLP0AZKLxeQGVpg

@name = create_account
POST {{baseUrl}}/accounts
content-type: application/json

{
    "name": "Davilson Junior",
    "email": "davilsonjunior.jobs@gmail.com",
    "password": "123456"
}

###

@name = authenticate
POST {{baseUrl}}/sessions
content-type: application/json

{
    "email": "davilsonjunior.jobs@gmail.com",
    "password": "123456"
}

###

@name = create_question
POST {{baseUrl}}/questions
content-type: application/json
Authorization: Bearer {{authToken}}

{
    "title": "Nova peegunta new 2",
    "content": "Conteudo da pergunta 3"
}

###

@name = fetch_recent_questions
GET {{baseUrl}}/questions
content-type: application/json
Authorization: Bearer {{authToken}}