@baseUrl = http://localhost:3333
@authToken = eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1ZjQ5YmEyOC0wZmJiLTQxMDctYWI4OC0zODkyYWNmZDY1NWEiLCJpYXQiOjE3MDMxNzUwMjh9.WbOeLc_x_GAK5n8Hb61Y8vewTDfyIEumqqTa56-psM26N-UOR9l0rhEIPsfp6MLfZ2PVgnDE_z829-iX1p7kA66aWXWp2GABwY2fzAANfRK7aIZAXSB9-ylilQWyaJtUmNGxOK92HATC40GioIkGjrTnOogt1X27J_iDqyxY7-AlO8o-ZiwTM9s52Dyv7fJMnUWI7bYHNd9tw00iR1EStw2a4z71L7ANxMPeH8nWei2xpnm8VJWUGITLt0m1CNFvNtl64X2dwwDVF1lyebSnTCkexrtcwUXXZ_JxbfMjp56iK5K7HnCCoTGYHan2jIrO9xBo__Jzhp9N13UWes9evQ

@name = create_account
POST {{baseUrl}}/accounts
content-type: application/json

{
    "name": "Davilson Junior",
    "email": "davilsonjunior.jobs@gmail.com",
    "password": "123456"
}

###

@name = authenticate
POST {{baseUrl}}/sessions
content-type: application/json

{
    "email": "davilsonjunior.jobs@gmail.com",
    "password": "123456"
}

###

@name = create_question
POST {{baseUrl}}/questions
content-type: application/json
Authorization: Bearer {{authToken}}

{
    "title": "Nova peegunta new 2",
    "content": "Conteudo da pergunta 3"
}

###

@name = fetch_recent_questions
GET {{baseUrl}}/questions
content-type: application/json
Authorization: Bearer {{authToken}}